### ISSUE TITLE
Special characters not encoded correctly in email

### ISSUE THREAD

**Issue by Kebap** [Mudlet/mudlet-package-repo#113]
i18n file contains text like `Bitte bestätige deine Emailadresse` with `ä`
Email sent shows text like `Bitte bestÃ¤tige deine Emailadresse` with `Ã¤`

**Comment by vadi2** [comment]
I suspect this needs to be wrapped with an [escape()](https://leafo.net/lapis/reference/utilities.html#functions/escape):

```lua
local message_subject = i18n("verify_email_subject", {self.config.website_name})
```

Cant test at the moment however, but let's try it once https://github.com/Mudlet/mudlet-package-repo/issues/114 is up and running.
