### ISSUE TITLE
Print only the package name after uploading

### ISSUE THREAD

**Issue by vadi2** [Mudlet/mudlet-package-repo#115]
#### Brief summary of issue / Description of requested feature:
The whole URL is printed right now instead of just the package name:

![image](https://user-images.githubusercontent.com/110988/109109720-1b023180-7736-11eb-9d0a-8bc042a5e8bb.png)

#### Steps to reproduce the issue / Reasons for adding feature:

1. Upload any sample package 
2. 
3.

**Comment by vadi2** [comment]
Interestingly new deployment didn't work:

![image](https://user-images.githubusercontent.com/110988/109263160-135c8e80-7803-11eb-9ff9-f6f652206078.png)

**Comment by Kebap** [comment]
Was not deployed or not fixed? :confused:

**Comment by vadi2** [comment]
Not sure. Let's try https://github.com/Mudlet/mudlet-package-repo/pull/118, I suspect the docker action needed upgrading.

**Comment by vadi2** [comment]
It was not deployed. Now it is, works fine:

![image](https://user-images.githubusercontent.com/110988/109317690-40359380-784d-11eb-8ca9-8e46bbd34038.png)
