### ISSUE TITLE
Login in with docker image doesn't seem to work as described

### ISSUE THREAD

**Issue by Edru2** [Mudlet/mudlet-package-repo#138]
The login information at https://github.com/Mudlet/mudlet-package-repo#via-docker seems to not be correct.
I just get Error: Invalid username or password

**Comment by vadi2** [comment]
Does user `mudletrepo`, password `pleasechangeme` give the same?

**Comment by Edru2** [comment]
okay I found out ```mudletrepo``` and ```pleasechangeme``` are the postgres db  username/password. 
For the website it is ```admin``` and  ```supersecretadminpass``` as seen in https://github.com/Mudlet/mudlet-package-repo/blob/development/config.lua
