### ISSUE TITLE
Migrate to in-database storage

### ISSUE THREAD

**Issue by vadi2** [Mudlet/mudlet-package-repo#43]
We've started out with on-disk storage (because that's what we knew) but for ease of management in kubernetes, it's best if nothing is stored on disk. Migrate storage of packages to the database instead.

**Comment by Edru2** [comment]
Thats not me giving up :sweat_smile: 
but I think it's probably not possible or at least not easy,
I checked the documentation at https://leafo.net/lapis/ and cannot find anything and as I checked the db schemas at https://github.com/leafo/lapis/blob/2560b545704d933b692b68986d15cfdcde091814/lapis/db/postgres/schema.lua#L286
I don't see anything which resembles a file as type (blob/file or something else)

But I'll continue looking into it

edit:
Maybe I'm also just looking at the wrong places

**Comment by vadi2** [comment]
Okay - fair point. It is not a good idea: https://github.com/leafo/lapis/issues/479#issuecomment-248704571

**Comment by vadi2** [comment]
So I'll look for something else for the kubernetes solution.

**Comment by vadi2** [comment]
Apparently https://min.io/ is the way to go.
