### ISSUE TITLE
Self host javascript, etc.

### ISSUE THREAD

**Issue by Kebap** [Mudlet/mudlet-package-repo#57]
There are quite a few external ressources: bootstrap, jquery, etc.

Better to serve them locally, than relying on 3rd party access.

Background:
https://csswizardry.com/2019/05/self-host-your-static-assets/
https://daan.dev/how-to/host-js-locally-crontab/

File `views/layout.etlua` lists these assets already:
* mudlet icon
   * [x] 32px
   * [x] 192px
   * [x] 180px
* bootstrap
   * [x] css
   * [x] js
* [x] jquery
* [x] popper

**Comment by Kebap** [comment]
After completing all this, I reviewed the versions we use.
Already, they were "a bit" outdated, and are preserved as such.
Maybe we should update, gain security improvements, etc?

Hopefully no compatibility breaks arise, but repo is in early stage.
Better upgrade now than later once we rely more heavily on them.

Bootstrap
We were linking 4.3.1 from February 2019
Current release 4.5.0 arrived in May 2020 
https://github.com/twbs/bootstrap/releases

jQuery
We use 3.3.1 from January 2018 (!)
Current version is 3.5.0 from May 2020
https://github.com/jquery/jquery/releases

Popper
We use 1.14.7 from January 2019
Current version is 2.4.0 (!) from May 2020
https://github.com/popperjs/popper-core/releases

**Comment by vadi2** [comment]
Yeah, for sure.
