### ISSUE TITLE
Static assets are all served as text/plain

### ISSUE THREAD

**Issue by vadi2** [Mudlet/mudlet-package-repo#65]
```
The stylesheet http://localhost:8080/static/bootstrap/4.5.0/css/bootstrap.min.css was not loaded because its MIME type, “text/plain”, is not “text/css”. register
The script from “http://localhost:8080/static/jquery/jquery-3.5.1.slim.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.
register
The script from “http://localhost:8080/static/popper.js/core@2.4.0/dist/umd/popper.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.
register
The script from “http://localhost:8080/static/bootstrap/4.5.0/js/bootstrap.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type.
```

They should be served as correct types instead.

**Comment by Kebap** [comment]
nginx conf should know that *.css is text/css and *.js is JavaScript MIME type and not text/plain at all.

http://nginx.org/en/docs/http/ngx_http_core_module.html#types says:
> A sufficiently full mapping table is distributed with nginx in the `conf/mime.types` file.

Search finds similar cases like:
https://nocurve.com/2014/02/24/how-i-wasted-an-entire-day-on-wrong-mime-type/

**Comment by vadi2** [comment]
Haven't looked too much into it, but we already have the [mime.types file](https://github.com/Mudlet/mudlet-package-repo/blob/development/mime.types).
