### ISSUE TITLE
Can modify other users' packages

### ISSUE THREAD

**Issue by Kebap** [Mudlet/mudlet-package-repo#77]
"Choose package to modify" should only list MY packages, not all including from other users

Additional checks should make prevent it, if I manually type in a package name of other users.

**Comment by vadi2** [comment]
Just asking the obvious, you didn't register as an admin?

**Comment by Kebap** [comment]
Oh, maybe

**Comment by Edru2** [comment]
That shouldn't be possible.
Only admins can modify every users package.

**Comment by Kebap** [comment]
Yes, I was an admin currently
